/** @type {import('next').NextConfig} */
const nextConfig = {
    images: {
        domains: [
            "static.fetchingapp.co.kr",
            "img.ssensemedia.com",
            "data.glamood.com",
            "media.endclothing.com",
            "www.yoox.com",
            "cdn-images.farfetch-contents.com",
            "lp.cosstores.com",
            "a2.cdn.hhv.de",
            "ko.club21.com",
            "tres-bien.com",
            "www.dr-adams.dk",
            "images.lvrcdn.com",
            "www.rei.com",
            "02.cdn37.se",
            "cdn.shopify.com",
            "static.fetchingapp.co.kr",
            "is4.fwrdassets.com",
            "data.glamood.com",
            "img.mytheresa.com",
            "ak-media.theory.com",
            "www.cultizm.com",
            "www.ln-cc.com",
            "media.sivasdescalzo.com",
            "017shop.ca",
            "a1.cdn.hhv.de",
            "img.brownsfashion.com",
            "image-cdn.hypb.st/https%3A%2F%2Fs3.store.hypebeast.com",
            "www.mrporter.com",
            "julianfashionstorage.blob.core.windows.net",
            "tres-bien.com",
            "d3vfig6e0r0snz.cloudfront.net",
        ],
    },
};

export default nextConfig;
